name: Build the page
on:  
  schedule:
  - cron:  '0 8,20 * * *'
  workflow_dispatch:
  
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Get library
        run: |
          python3 -m pip install -r requirements.txt
          sudo apt-get install poppler-utils
      - name: Make build folder
        run: mkdir build
      - name: Get pages count
        shell: bash
        env:
          DRP_AUTH_TOKEN: ${{ secrets.DRP_AUTH_TOKEN }}
          FINISHED: ${{ secrets.FINISHED }}
          WHEN: ${{ secrets.WHEN }}
        run: python3 drp.py
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
